export const TOGGLE_THEME = "toggle-theme"
export const ADD_FILES = "add-files"
export const DELETE_FILE = "delete-file"
export const SET_FILES_OUTPUT_FORMAT = "set-files-output-format"
export const SET_CURRENT_FILE_TO_CONFIG = "set-current-file-to-config"
export const SET_FILE_OUTPUT_PARAMS = "set-file-output-params"
export const SET_FILES_SHARED_OUTPUT_PARAMS = "set-files-shared-output-params"
export const SET_FILE_CONVERTION_IS_PROCESSING =
  "set-file-convertion-is-processing"
export const SET_FILE_CONVERTION_SUCCESS = "set-file-convertion-success"
export const SET_FILE_CONVERTION_ERROR = "set-file-convertion-error"
export const RESET_ALL_FILE_STATE = "reset-all-file-state"